### ISSUE TITLE
issue about docker

### ISSUE THREAD

**Issue by qixuxiang** [Hananel-Hazan/bindsnet#102]
Thanks for your awesome codeshare!

I am new to docker and I do not know how to use dockerfile.

When I run the command

```
docker image build .
```

I check docker images and find a image whose container id and image id is none, maybe it is the docker images I need. But I can not `docker run` the images.

So what should do to use it? Thanks a lot!

**Comment by hqkhan** [comment]
Hi @qixuxiang. If the `IMAGE ID` is `<none>` then something likely went wrong although I've never seen that before. Just to check: Are you referring to `REPOSITORY` and `TAG` as being `<none>` after you ran the command: `docker image build .`? If this is what it looks like
![image](https://user-images.githubusercontent.com/22674069/43291311-f890f5de-90fe-11e8-88b7-dd0a53e22615.png)

then it's an easy fix. You can rename images that you've created by running the command: `docker tag <IMAGE ID> <NAME_THAT_YOU_WANT>`. To run a container from that image and get a terminal inside, simply do `docker run -it <IMAGE_NAME> bash`.

If that wasn't the case, it'd be useful to see a screenshot of what you're saying to further help with this. There is something weird going on with `docker pull hqkhan/bindsnet` therefore unless you weren't doing so already, I'd suggest you clone the repo and work from there. I will provide a step by step way of working with bindsnet through a docker container below:

1) Clone repo using `git clone https://github.com/Hananel-Hazan/bindsnet`

![image](https://user-images.githubusercontent.com/22674069/43291085-311ca368-90fe-11e8-9dab-f0836c54b99e.png)

2) Go into newly cloned directory by `cd bindsnet` and run `docker image build .`

![image](https://user-images.githubusercontent.com/22674069/43291148-7944f186-90fe-11e8-92fd-73f559d06e92.png)

It should be downloading relevant packages. Once its done it should look like this:
![image](https://user-images.githubusercontent.com/22674069/43291302-f09354bc-90fe-11e8-9197-7f3ca467e83a.png)

3) Rename the image by issuing 
`docker tag 0bc51f9781d0 bindsnet` 
Note: `bindsnet` can be whatever you want it to be.

![image](https://user-images.githubusercontent.com/22674069/43291454-8681aeba-90ff-11e8-8cea-0ad9267dd802.png)

4) Create a container off of `bindsnet` image and obtain a bash terminal inside by issuing
`docker run -it bindsnet bash` 
Note: if your image name was not `bindsnet`, use your own image name there.

![image](https://user-images.githubusercontent.com/22674069/43291565-e7234bb6-90ff-11e8-8911-047e06795d1d.png)

After that, simply run python and test if bindsnet is working. 

I hope this helps. Let me know if there's anything else that I can help with. 

P.s : `docker-compose` capabilities coming later to allow for mounting volumes and running jupyter notebooks.

**Comment by qixuxiang** [comment]
Hi @hqkhan, Thanks for your elaborative answer! This is the most careful answer I have ever seen in github, you are a true life saver!

**Comment by hqkhan** [comment]
Happy to help!
