### ISSUE TITLE
Weights Decaying 

### ISSUE THREAD

**Issue by Hananel-Hazan** [Hananel-Hazan/bindsnet#126]
Add a weights decaying for Hebbian learning

**Comment by djsaunde** [comment]
I think it would be best to implement this in the abstract base class `LearningRule`, as part of its `update()` function. Then, any class that subclasses `LearningRule` would call the `LearningRule`'s `update()` function as part of its `update()`, where weight decay would be implemented.

We also need to decided what the form of the weight decay is. Is it something like:

`w -= delta`  # for delta small

or:

`w -= delta * w`  # for delta small

or something else? How is it implemented in Chetan's code? On another note, we should create a private GitHub repository with Chetan's code so we can all access it.

**Comment by Hananel-Hazan** [comment]
Agreed

**Comment by djsaunde** [comment]
Has Chetan's code been published in a private repo? If so, could you invite me to collaborate on it?
