### ISSUE TITLE
Logistic regression evaluation method

### ISSUE THREAD

**Issue by djsaunde** [Hananel-Hazan/bindsnet#134]
I'd like to implement a logistic regression function in the `bindsnet.evaluation` module. This will be a sort of principled way to evaluate network's learning spiking behavior, at least if we are doing classification. I'll likely be using `sklearn.linear_model.LogisticRegresssion` to do this.

**Comment by Hananel-Hazan** [comment]
Good idea, a general evaluation function.  I think @dee0512 already have something that he use for the probability neurons
