### ISSUE TITLE
Supporting none-1.0 dt

### ISSUE THREAD

**Issue by godelicbach** [Hananel-Hazan/bindsnet#151]
I tried to change the value of dt from 1.0 to 0.1, but it didn't fit in the pipeline with other components. The error I encountered was difference of number of timesteps between encoded input's and network. Since encoded input's number of timesteps is `time` while network's number of timesteps is `time/dt`. I was thinking about resolving this issue, but I found that it requires redesigning almost every encoding functions. Any idea about this? Or am I missing something?

Thank you.

**Comment by djsaunde** [comment]
Hi @godelicbach,

An easy way to fix this is to create a new `Pipeline` variable `self.sim_time = int(time / dt)`, and pass this into the encoding functions. Or, we could redesign the encoding functions themselves (which are sorely in need of an update anyway) by having them accept a `dt` argument as well.

Thoughts?

**Comment by djsaunde** [comment]
After a bit more thought, I think it makes more sense to have all `encoding` functions accept a `dt` argument. For example, in the `poisson` encoding, the spike train generation must depend on the simulation time step in order to achieve the correct firing rates.

**Comment by djsaunde** [comment]
This has been resolved by #152.
