### ISSUE TITLE
[Bug Maybe?][model: IncreasingInhibitionNetwork][Weight Initialization]

### ISSUE THREAD

**Issue by janilbols** [Hananel-Hazan/bindsnet#174]
hi, I'm looking into the code for model [IncreasingInhibitionNetwork](https://github.com/Hananel-Hazan/bindsnet/blob/master/bindsnet/models/__init__.py), and is a bit confused about line 228-229:

```
inhib = -self.start_inhib * np.sqrt(euclidean([x1, y1], [x2, y2]))
w[i, j] = min(self.max_inhib, inhib)
```
I think it's used for initializing the weights `w` of connection, depend on the distance between two neurons.
```
for i in range(self.n_neurons):
            for j in range(self.n_neurons):
                if i != j:
                    x1, y1 = i // self.n_sqrt, i % self.n_sqrt
                    x2, y2 = j // self.n_sqrt, j % self.n_sqrt

                    inhib = -self.start_inhib * np.sqrt(euclidean([x1, y1], [x2, y2]))
                    w[i, j] = min(self.max_inhib, inhib)

        recurrent_output_conn = Connection(
            source=self.layers['Y'], target=self.layers['Y'], w=w, wmin=-self.max_inhib, wmax=0
        )
        self.add_connection(recurrent_output_conn, source='Y', target='Y')
```
As the default initial value for `start_inhib=1.0, max_inhib=100`, but we expect the weights to be 
negative numbers; you set a '-' for `inhib` and forget to set for `self.max_inhib`, that `inhib` will be negative and `self.max_inhib` is still positive, and this will make `min(self.max_inhib, inhib)`always equal to`inhib`.

In this way you might  want 
`w[i,j] = max(-self.max_inhib, inhib)` , 

or maybe change both line to 
```
inhib = self.start_inhib * np.sqrt(euclidean([x1, y1], [x2, y2]))
w[i, j] = -min(self.max_inhib, inhib)
```

I don't know whether my understanding is correct, could you have a look at it?

**Comment by dee0512** [comment]
Yes. You are right. You can create a PR. The second option is better since it is easier to understand.

**Comment by janilbols** [comment]
Alright, I've create a PR.
