### ISSUE TITLE
Error response from daemon: manifest for hqkhan/bindsnet:latest not found

### ISSUE THREAD

**Issue by zhouxzh** [Hananel-Hazan/bindsnet#177]
I want to install bindsnet by docker.
But when I want to pull the docker image by command "docker pull hqkhan/bindsnet", I got the following error message "Error response from daemon: manifest for hqkhan/bindsnet:latest not found"

Xianzhong Zhou
Guangdong University of Technology

**Comment by djsaunde** [comment]
@hqkhan I know you're not involved with this project any more, but do you happen to know why this error is occuring? I'm not familiar with Docker. Let me know if you can't / don't want to handle this, and I'll try to figure it out.

**Comment by hqkhan** [comment]
@djsaunde Sorry for being mia. Didn't know that my UMass email had been deactivated and I never got this notification. I will take a look at this when I get back from work.

**Comment by hqkhan** [comment]
Hi @zhouxzh. I have added the `latest` tag to the docker repo. It should allow you to pull now. Let me know if there are questions.
