### ISSUE TITLE
refract_count going negative

### ISSUE THREAD

**Issue by sinkingsugar** [Hananel-Hazan/bindsnet#178]
I'm having a issue with refract_count going always negative.
I noticed something that might actually be a bug.

For example in:
https://github.com/Hananel-Hazan/bindsnet/blob/197cfbd00bfd2c270b2232f7eb9cca66f10bda42/bindsnet/network/nodes.py#L295

Shouldn't this be `(self.refrac_count > 0).float()` ? Considering floating point precision this will likely never be back at `0` but more like e.g. `tensor([2.6822e-07])`

**Comment by djsaunde** [comment]
Thanks for spotting this, it's definitely a problem.
