### ISSUE TITLE
refrac_count going negative part 2

### ISSUE THREAD

**Issue by sinkingsugar** [Hananel-Hazan/bindsnet#186]
https://github.com/Hananel-Hazan/bindsnet/blob/05e07721d2d93f95af1391c5bd8cb0d98f5ec929/bindsnet/conversion/__init__.py#L141

Just like #178 This should probably be `self.refrac_count > 0` considering floating point precision issues/fast math etc.

**Comment by Hananel-Hazan** [comment]
That is correct.
Thanks for point it out
