### ISSUE TITLE
Inefficient implementation of connection normalization in network.run

### ISSUE THREAD

**Issue by dee0512** [Hananel-Hazan/bindsnet#189]
```
        for c in self.connections:
            self.connections[c].normalize()
            self.connections[c].normalize_by_max()
            self.connections[c].normalize_by_max_from_shadow_weights()
```

The above code adds three if statements per connection each time network.run is called. We can implement it more efficiently.

**Comment by djsaunde** [comment]
Yeah. I'm not sure we even want all three functions implemented for all `Connection` types; might make sense implement them as-needed instead of maintaining them in the codebase.
