### ISSUE TITLE
Implementation of different inhibition mechanisms

### ISSUE THREAD

**Issue by lehahoang** [Hananel-Hazan/bindsnet#192]
Hi,
I am trying to test the ideas from the "Unsupervised Learning with Self-Organizing Spiking Neural Networks" work (arXiv:1807.09374), however, it is still not working. 
I would like to ask if any example of inhibition mechanisms presented in this paper available in Bindsnet?
Thank you.

**Comment by djsaunde** [comment]
Hi @lehahoang,

In general, we try to keep complicated experiments out of the BindsNET repository. See [here](https://github.com/djsaunde/bindsnet_experiments/tree/master/experiments/mnist) and [here](https://github.com/djsaunde/bindsnet_experiments/blob/master/experiments/mnist/two_level_inhibition.py) for the BindsNET adaptation of the experiments from that paper.

Alternatively, the original code for that paper is located [here](https://github.com/djsaunde/lm-snn). However, it is very messy / difficult to follow.

**Comment by lehahoang** [comment]
Hi @djsaunde,
Thank you for your kind reply.
I think it is better if you can put examples as many as possible. From my perspective, I found it easy to use BindsNET rather than Brian2 simulator.
Best regards,

**Comment by djsaunde** [comment]
No problem. The BindsNET experiments repository has lots of examples (github.com/djsaunde/bindsnet_experiments). You can install it with `pip install -e .` in the top-level directory.
