### ISSUE TITLE
supervised_mnist.py error

### ISSUE THREAD

**Issue by AratorField** [Hananel-Hazan/bindsnet#197]
I have built library from source.
When running `python supervised_mnist.py --gpu` I am getting following error.

> Loading training images from serialized object file.
> 
> Loading training labels from serialized object file.
> 
> Begin training.
> 
> Progress: 0 / 50000 (0.0000 seconds)
> Progress: 10 / 50000 (1.6048 seconds)
> Progress: 20 / 50000 (1.7189 seconds)
> Progress: 30 / 50000 (1.5952 seconds)
> Progress: 40 / 50000 (1.5939 seconds)
> Progress: 50 / 50000 (1.5914 seconds)
> Progress: 60 / 50000 (1.5920 seconds)
> Progress: 70 / 50000 (1.5892 seconds)
> Progress: 80 / 50000 (1.5927 seconds)
> Progress: 90 / 50000 (1.5949 seconds)
> Progress: 100 / 50000 (1.5965 seconds)
> Progress: 110 / 50000 (1.5923 seconds)
> Progress: 120 / 50000 (1.5900 seconds)
> Progress: 130 / 50000 (1.5927 seconds)
> Progress: 140 / 50000 (1.5915 seconds)
> Progress: 150 / 50000 (1.5953 seconds)
> Progress: 160 / 50000 (1.5927 seconds)
> Progress: 170 / 50000 (1.5882 seconds)
> Progress: 180 / 50000 (1.5892 seconds)
> Progress: 190 / 50000 (1.5924 seconds)
> Progress: 200 / 50000 (1.5946 seconds)
> Progress: 210 / 50000 (1.5924 seconds)
> Progress: 220 / 50000 (1.5938 seconds)
> Progress: 230 / 50000 (1.5915 seconds)
> Progress: 240 / 50000 (1.5905 seconds)
> Progress: 250 / 50000 (1.5894 seconds)
> Traceback (most recent call last):
>   File "supervised_mnist.py", line 123, in <module>
>     % (accuracy['all'][-1], np.mean(accuracy['all']), np.max(accuracy['all'])))
>   File "~/numpy/core/fromnumeric.py", line 3118, in mean
>     out=out, **kwargs)
>   File "~/numpy/core/_methods.py", line 85, in _mean
>     ret = ret.dtype.type(ret / rcount)
> AttributeError: 'torch.dtype' object has no attribute 'type'

**Comment by djsaunde** [comment]
Hi @AratorField,

I pushed a fix to this to master. Let me know if you have any more problems.
