### ISSUE TITLE
How to use the rank_order encoding

### ISSUE THREAD

**Issue by rachmadvwp** [Hananel-Hazan/bindsnet#202]
Hi,
I'd like to ask, how to use the rank-order encoding.
I tried to use it for some network models, e.g., eth_mnist with the following lines of codes: 

> from bindsnet.encoding import rank_order_loader
> data_loader = rank_order_loader(data=images, time=time, dt=dt)

However, it gave me the following error:

> Traceback (most recent call last):
>   File "eth_mnist.py", line 132, in <module>
>     sample = next(data_loader)
>   File "/.../bindsnet/lib/python3.6/site-packages/bindsnet/encoding/__init__.py", line 207, in rank_order_loader
>     yield rank_order(datum=data[i], time=time, dt=dt)  # Encode datum as rank order-encoded spike trains.
>   File "/.../bindsnet/lib/python3.6/site-packages/bindsnet/encoding/__init__.py", line 173, in rank_order
>     assert datum >= 0, 'Inputs must be non-negative'
> RuntimeError: bool value of Tensor with more than one value is ambiguous

What should I do to fix this?
Thanks in advance

Best regards

**Comment by djsaunde** [comment]
I made a PR (#203) to fix this. Please let us know if you have any other problems.

**Comment by rachmadvwp** [comment]
I made changes like what PR(#203) show, but the problem remains the same. Do I miss something or some steps? Thanks in advance.
Best regards

**Comment by djsaunde** [comment]
Hm, did you install the package in editable mode (`pip install -e .` in the root directory)? Changing [this line](https://github.com/Hananel-Hazan/bindsnet/blob/8fc94c6188856666b7721e0934f835e1f34a6af9/bindsnet/encoding/__init__.py#L173) to `assert (datum >= 0).all(), 'Inputs must be non-negative'` should fix the error.

**Comment by rachmadvwp** [comment]
Now it is running fine. Thanks a lot for the help. 
Best regards
