### ISSUE TITLE
Reward is not actually accumulated

### ISSUE THREAD

**Issue by Huizerd** [Hananel-Hazan/bindsnet#204]
https://github.com/Hananel-Hazan/bindsnet/blob/e4ebfadc0d52f6356ed8356d595f7adb7f69f6ed/bindsnet/pipeline/__init__.py#L175

The obtained reward `self.reward` is not actually accumulated into `self.accumulated_reward`, causing it to remain zero (this shows when plotting reward).

**Comment by djsaunde** [comment]
Can you add `self.accumulated_reward = 0` in the `Pipeline.reset()` function?

**Comment by Huizerd** [comment]
Ok, done!
