### ISSUE TITLE
cannot import name 'CurrentLIFNodes'

### ISSUE THREAD

**Issue by zhouxzh** [Hananel-Hazan/bindsnet#208]
I just install bindsnet with the lastest version from github.
But when I want to run the example LIFNodes vs. CurrentLIFNodes, I get the error "cannot import name 'CurrentLIFNodes'". Then I go the file nodes, I also cannot find out the object CurrentLIFNodes.
Have the object "CurrentLIFNodes" already been deleted?

**Comment by Hananel-Hazan** [comment]
Thanks @zhouxzh , I restored the function.  #209
