### ISSUE TITLE
Weight clamping ineffective

### ISSUE THREAD

**Issue by Huizerd** [Hananel-Hazan/bindsnet#212]
`Connection` gives you the possibility of clamping your weights to a range `wmin`-`wmax`: https://github.com/Hananel-Hazan/bindsnet/blob/f640fb602c6b550b4c9858ee533848fc3c02f135/bindsnet/network/topology.py#L136

However, this clamping doesn't seem to be very effective, as it happens in the `super` call to `LearningRule`:
https://github.com/Hananel-Hazan/bindsnet/blob/f640fb602c6b550b4c9858ee533848fc3c02f135/bindsnet/learning/__init__.py#L55

and weights are used in `Network.get_inputs`, which calls `Connection.compute`:
https://github.com/Hananel-Hazan/bindsnet/blob/f640fb602c6b550b4c9858ee533848fc3c02f135/bindsnet/network/topology.py#L173

This in itself wouldn't be a problem, if it weren't for the fact that weights can be increased/decreased beyond `wmin`/`wmax` between the clamping and the actual use, see for example here:
https://github.com/Hananel-Hazan/bindsnet/blob/f640fb602c6b550b4c9858ee533848fc3c02f135/bindsnet/learning/__init__.py#L535

Is this intended behaviour, am I missing something, or does this indeed seem wrong? I can do something about this, but I was wondering about your preferred way of solving this.

**Comment by djsaunde** [comment]
@Huizerd good catch! I think the solution would be to put the call to `super().update()` at the end of the `LearningRule`s `update()`s.
