### ISSUE TITLE
Bug when wmin or wmx is none

### ISSUE THREAD

**Issue by dee0512** [Hananel-Hazan/bindsnet#222]
[this](https://github.com/Hananel-Hazan/bindsnet/blob/master/bindsnet/network/__init__.py#L204)
```
# Ensure weights are correctly clamped
            assert ((self.connections[c].w <= self.connections[c].wmax).all() and (self.connections[c].w` >= self.connections[c].wmin).all())
```

Please remove this. There is no need for this check. It is also adding computation every single timestep.

**Comment by djsaunde** [comment]
I removed it in #219
