### ISSUE TITLE
Gitter chat room

### ISSUE THREAD

**Issue by djsaunde** [Hananel-Hazan/bindsnet#226]
@Hananel-Hazan what do you think of creating a [Gitter](https://gitter.im) room for chatting with people who use BindsNET? It could be a good place for people to ask for help. Since you're the owner of the repo, I believe you're the only person who can create it.

**Comment by dee0512** [comment]
This would be helpful

**Comment by Hananel-Hazan** [comment]
Done.
Gitter chat room is https://gitter.im/bindsnet_/community

**Comment by djsaunde** [comment]
Thanks!
