### ISSUE TITLE
Value Error in network example 

### ISSUE THREAD

**Issue by sabriinan** [Hananel-Hazan/bindsnet#227]
Hello, I was trying to run the first example (poisson encoding) at [https://bindsnet-docs.readthedocs.io/bindsnet.network.html#module-bindsnet.network](url), and it gives this error: 

```
  File "D:/python projects/bindsnet/untitled2.py", line 44, in <module>
    axes[i].matshow(spikes[layer], cmap='binary')

  File "D:\Anaconda3\envs\spyder\lib\site-packages\matplotlib\axes\_axes.py", line 7800, in matshow
    nr, nc = Z.shape

ValueError: too many values to unpack (expected 2)
```
when i look at `spikes[layers].shape`, it is `torch.Size([1, 100, 5000])`, i don't understand what the first axis is for? 

Thank you!

**Comment by djsaunde** [comment]
Hi @sabriinan, this can be fixed by changing `data = 15 * torch.rand(1, 100)` to `data = 15 * torch.rand(100)`. We'll make this change in the doc string.
