### ISSUE TITLE
RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor

### ISSUE THREAD

**Issue by rachmadvwp** [Hananel-Hazan/bindsnet#238]
Hi, 
Firstly, I'd like to say sorry since I wasn't able to reply the last thread that I created. But thanks for the answers, it was really helpful.
Now, I'd like to ask other thing. I tried to run cifar-10 on GPU, but I got this error.

> $ python cifar10_env.py --gpu
> Begin training.
> 
> Progress: 0 / 50000 (0.0000 seconds)
> Traceback (most recent call last):
>   File "cifar10_env.py", line 137, in <module>
>     pipeline.step()
>   File ".../bindsnet/bindsnet/pipeline/__init__.py", line 184, in step
>     self.encoded[inpt] = self.encoding(self.obs, time=self.time, dt=self.network.dt, **kwargs)
>   File ".../bindsnet/bindsnet/encoding/__init__.py", line 127, in poisson
>     rate[datum != 0] = 1 / datum[datum != 0] * (1000 / dt)
> RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor

I think it is a simple problem but since I'm still new to python, could you please help me to solve this fast. Thanks a lot for the help.
Best regards.

**Comment by Hananel-Hazan** [comment]
Hi @rachmadvwp 
I run it now and it execute without an issue.
Please pull the last BindsNET code from master. There where couple of changes in the last builds.

**Comment by djsaunde** [comment]
Hi @rachmadvwp,

No problem. By the way, you can still respond to threads on issues that have been closed.

PR #239 should fix your problem.
