### ISSUE TITLE
Testing an trained network

### ISSUE THREAD

**Issue by alexmaraval** [Hananel-Hazan/bindsnet#241]
Hi,

This is a follow-up question to [issue#73](https://github.com/Hananel-Hazan/bindsnet/issues/73) where the question about testing was asked.
I read the code from the [bindsnet_experiments](https://github.com/djsaunde/bindsnet_experiments/tree/master/experiments) and if I'm correct, testing is essentially 
- presenting test data to a network identical to the trained one except that it has no update rules,
- this test network is initialised with the weights of the trained network,  and
- neuron assignments (and proportions, rates, ...) updated by the network during training are used and not modified.

So if the above is correct, my question is : if learning rules were not removed, would that make the testing procedure invalid ? Is there any other way to test the network ?

Best,

P.S. thanks for this library, it's great.

**Comment by djsaunde** [comment]
Hi @alexmaraval,

> if learning rules were not removed, would that make the testing procedure invalid ? Is there any other way to test the network?
There's no one "valid" way to test the network; what we did in the script you mentioned happened to work well for our use case / experiments. You're free to come up with your own methods of evaluating trained networks, which may or may not include learning (or other adaption) during the test phase.

> P.S. thanks for this library, it's great.
Thanks! :smile:
