### ISSUE TITLE
Shape of tensors during convolutions

### ISSUE THREAD

**Issue by k-chaney** [Hananel-Hazan/bindsnet#242]
For Conv2dConnection, since it utilizes pytorch's conv2d operator it is inherently constrained by the same input expectations, which is BxCxHxW.

Inside of examples/mnist/conv_mnist.py the shape of the tensors go as follows
Line 120 - images has shape - torch.Size([60000, 28, 28])
Line 125 - images is fed to poisson_loader which effectively turns it into - torch.Size([60000, 50, 28, 28])
Line 147 - a single spike stream is pulled out with shape - torch.Size([50, 28, 28])
               - this is then formatted through two unsqueezes which becomes shape -  torch.Size([50, 1, 1, 28, 28])
Which plays nicely with the sampling in bindsnet/network/__init__.py (line 286) which turns it into torch.Size([1,1,28,28]) and in turn is the shape that conv2d expects.

However this exact formula breaks down with the CIFAR10 dataset which constructs a tensor of shape - torch.Size([50000, 32, 32, 3]) - and thus transpositions must be done.

This complexity isn't mirrored in a non-convolutional network (such as the one defined in examples/cifar10/supervised_cifar10.py).

My proposal would be to standardize the output from the supported datasets to work with both setups.

My suggestion would be to follow in pytorch's footsteps and leverage their data loading pipeline and after the DataLoader produce TxBxCxHxW. Ultimately for larger datasets (such as MVSEC, DDD17, and others) this paradigm will be significantly more flexible.

One concern would be breaking some of the backwards compatibility in other portions of the code (this can be helped a bit through keeping the primary access functions around and just deprecate them for removal later).

I'm more than happy to work on this and can probably have something for review by Tuesday or Wednesday depending on my exact schedule.

**Comment by djsaunde** [comment]
Yeah, I think this is a reasonable thing to do. It might make sense to directly leverage `torchvision.datasets` (instead of `bindsnet.datasets`; or `bindsnet.datasets` would lightly wrap it?) so we no longer have to maintain things like MNIST, CIFAR-10, etc. and benefit from datasets they support which we currently do not.

**Comment by Hananel-Hazan** [comment]
Merged #243
