### ISSUE TITLE
When this line in a code is working on?

### ISSUE THREAD

**Issue by chatterboy** [Hananel-Hazan/bindsnet#246]
Hello, I got something weird when I am looking at the code. It is a part of `Poisson` method in [bindsnet/bindsnet/encoding/__init__.py](https://github.com/Hananel-Hazan/bindsnet/blob/master/bindsnet/encoding/__init__.py#L104). The line is written such as `intervals[:, datum != 0] += (intervals[:, datum != 0] == 0).float()`. I don't understand It is working properly.

Thank you.

**Comment by Hananel-Hazan** [comment]
Can you please elaborate why its not working properly?
