### ISSUE TITLE
__getitem__ outputs should support integer indexing

### ISSUE THREAD

**Issue by djsaunde** [Hananel-Hazan/bindsnet#252]
https://github.com/Hananel-Hazan/bindsnet/blob/009a8024beb468c41bd8b00bdaa8a913da2391a7/bindsnet/datasets/spoken_mnist.py#L78

See https://pytorch.org/docs/stable/_modules/torch/utils/data/dataset.html#Dataset.

CC @k-chaney

**Comment by djsaunde** [comment]
Sorry, didn't make sense. Though, should we return tuples instead of dictionaries with `__getitem__`? How does `torch` do this?

**Comment by k-chaney** [comment]
`torch` handles all of this under the hood inside of their `torch.utils.data._utils.collate.default_collate` function (it's something close to that extension here's the url https://github.com/pytorch/pytorch/blob/master/torch/utils/data/_utils/collate.py). It is able to deal with any standard container that is returned tuple, dict, list, etc. All that is required is the same container from each of the workers and `default_collate` will construct the full batch inside of a mirror of the container.
