### ISSUE TITLE
Encoder in environment.GymEnvironment

### ISSUE THREAD

**Issue by Hananel-Hazan** [Hananel-Hazan/bindsnet#254]
Trying to use environment.GymEnvironment in BindsNET without encoder lead to a error in loading.

@k-chaney, I think encoder should be an option not mandatory.

**Comment by Hananel-Hazan** [comment]
#255

**Comment by djsaunde** [comment]
Yeah, @k-chaney, is it possible to default to `NullEncoder`?

By the way, I think spike_encoders.py should be kept in the `bindsnet/encoders/` folder, and I think it'd be best if you put all the `Encoder` classes in `bindsnet/encoders/__init__.py`.

**Comment by Hananel-Hazan** [comment]
I think that by default if encoder, or image_encoder and label_encoder need to be set to NullEncoder

That can solve the issue and my commit need to be cancel

**Comment by k-chaney** [comment]
Sorry about the delay, I've been diving into the other feature I'm working on. This seems like a reasonable change. I just pushed a branch `chaney/gym_env_encoder_fix` that deals with this as described. 

1) Do we want the encoders to be in their own module or should we leverage the encodings module that already exists?
2) For the `GymEnvironment` the encoder default is `NullEncoder`.
3) For the `torchvision.dataset` wrapping, we should probably keep them as mandatory positional arguments and just allow `None` to convert to `NullEncoder` in the constructor. This maintains the format of bindsnet arguments first and then the dataset specific arguments second and as keyword arguments.

**Comment by Hananel-Hazan** [comment]
Thanks @k-chaney. 
Yes, leveraging the encoder module is preferred. 2 and 3 look good.

**Comment by djsaunde** [comment]
Yeah, I think should keep both the functional and class interfaces to the encodings in `bindsnet/encoding/__init__.py`.

**Comment by k-chaney** [comment]
Just pushed some changes to fix 1. I'll submit a pull request.
