### ISSUE TITLE
DiehlAndCook2015 testing 

### ISSUE THREAD

**Issue by WongyuLee1729** [Hananel-Hazan/bindsnet#256]
In the MNIST example, DiehlAndCook2015, I finished training and saved for testing. 
Now, I called the network for testing and turned off the learning. 
However, when I check the theta and weight in layers['Ae' ],  I noticed that those two constantly changes every time I run the code.

below is how I turned off the STDP (postpre), the learning method. 

network = load_network('trained_data') #loaded the trained data
network.learning = False # <= turn off the learning rule.  

So I'm wondering how to turn off the learning in the testing?

Thank you. 

Best wishes. 

Wongyu.

**Comment by Hananel-Hazan** [comment]
Thank you for bring this to our attention. 
I'll check it more deeply later on. 

But for now, the easy solution is, after loading, use clone of the network object for every test.

**Comment by djsaunde** [comment]
@WongyuLee1729 to turn off the theta adaptation manually, set `network.layers['Ae'].theta_plus = 0` and `network.layers['Ae'].theta_decay = 0`.

@Hananel-Hazan it probably makes sense to turn off theta adaption (adaptive threshold) as part of `network.learning = False`. I can implement this.

**Comment by WongyuLee1729** [comment]
@Hananel-Hazan 
@djsaunde 
I already figure that out. check out my code below. 

You may also want to check spike_record for testing. That is, 

spike_record[i % update_interval] = spikes['Ae'].get('s').t()

if you plot voltage monitor, it does not match to it. 
I also figure that out though. 



# ==================================================================
# turn off STDP & theta value
w = network.connections[('X','Ae')].w #= 0.3 * torch.rand(784, n_neurons) 
network.add_connection(topol.Connection(network.layers['X'], network.layers['Ae'], w=w, update_rule=None, nu=(1e-4, 1e-2), wmin=0.0, wmax=1.0, norm=78.4, decay=None), source='X', target='Ae')

network.layers['Ae'].theta_plus = 0
network.layers['Ae'].theta_decay = 0

**Comment by djsaunde** [comment]
Here's a small example demonstrating that weight changes are disabled by setting loading the network with `learning=False`:

```
import torch
from bindsnet.network import Network
from bindsnet.network.nodes import Input, LIFNodes
from bindsnet.network.topology import Connection
from bindsnet.network.monitors import Monitor
from bindsnet.learning import PostPre
from bindsnet.network import load


time = 50

network = Network()

network.add_layer(
    layer=Input(n=100, traces=True),
    name='X'
)
network.add_layer(
    layer=LIFNodes(n=100, traces=True),
    name='Y'
)

network.add_connection(
    Connection(
        source=network.layers['X'],
        target=network.layers['Y'],
        update_rule=PostPre,
        wmin=0.,
        wmax=1.,
        nu=(0.001, 0.01)
    ),
    source='X',
    target='Y'
)

w1 = network.connections['X', 'Y'].w

network.add_monitor(
    Monitor(
        obj=network.layers['X'],
        state_vars=['s'],
        time=time
    ),
    name='X_s'
)
network.add_monitor(
    Monitor(
        obj=network.layers['Y'],
        state_vars=['s', 'v'],
        time=time
    ),
    name='Y_s_v'
)
network.add_monitor(
    Monitor(
        obj=network.connections['X', 'Y'],
        state_vars=['w'],
        time=time
    ),
    name='X_Y_w'
)

network.run(
    inpts={
        'X': torch.bernoulli(
            0.1 * torch.rand(
                time, network.layers['X'].n
            )
        )
    },
    time=time
)

w2 = network.connections['X', 'Y'].w

print(f'Should be non-zero: {(w2 - w1).abs().sum().item():.2f}')

network.save(file_name='network.pt')
network = load(file_name='network.pt', learning=False)

network.run(
    inpts={
        'X': torch.bernoulli(
            0.1 * torch.rand(
                time, network.layers['X'].n
            )
        )
    },
    time=time
)

w3 = network.connections['X', 'Y'].w

print(f'Should be zero: {(w3 - w2).abs().sum().item()}')
```

**Comment by djsaunde** [comment]
#259 disables adaptive thresholds when `network.learning = False`.
