### ISSUE TITLE
Queries on learning rule scripts

### ISSUE THREAD

**Issue by rachmadvwp** [Hananel-Hazan/bindsnet#263]
Hi,
I'd like to ask about the following scripts in PostPre learning rule.
In the connection update, there are scripts:
```
source_s = self.source.s.view(-1).float()
source_x = self.source.x.view(-1)
target_s = self.target.s.view(-1).float()
target_x = self.target.x.view(-1)
```
I just don't get what the 's' and 'x' mean here? Could you plesae let me know what they represent?
Because it is important to understand the following parts: `torch.ger(source_s, target_x)` and `torch.ger(source_x, target_s)`.

Thanks a lot.
Best regards

**Comment by djsaunde** [comment]
Hi @rachmadvwp,

's' refers to spikes, and 'x' refers to _spike traces_, which keeps a decaying history of the most recent spike, implemented as a exponentially decaying quantity which is set to 1 when a spike occurs.

`torch.ger(source_s, target_x)` computes the outer product between spikes in the "source" layer (from which the connection originates) and the spikes traces in the "target" layer (to which the connection connects).

`PostPre` implements the "online" implementation of STDP; see [here](http://www.scholarpedia.org/article/Spike-timing_dependent_plasticity#Online_implementation_of_STDP_models), in particular, see Figure 2.

**Comment by rachmadvwp** [comment]
I know the STDP and the mechanism which is supposed to be implemented in the code.
Since I'm still learning python, I just wanted to ensure whether my guess was correct.
Thanks for the answer, it is really helpful.

**Comment by rachmadvwp** [comment]
Hi @djsaunde 
I was trying to do training using codes from the experiment repo on gpu.
However, I got this following error:

Traceback (most recent call last):
  File "diehl_and_cook_2015.py", line 354, in <module>
    main(**args)
  File "diehl_and_cook_2015.py", line 258, in main
    print('\t%s: %.2f' % (scheme, float(np.mean(curves[scheme]))))
  File "/anaconda3/envs/BindsNET/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3118, in mean
    out=out, **kwargs)
  File "/anaconda3/envs/BindsNET/lib/python3.7/site-packages/numpy/core/_methods.py", line 85, in _mean
    ret = ret.dtype.type(ret / rcount)
AttributeError: 'torch.dtype' object has no attribute 'type'

I think it is a simple problem and tried to solve it, unfortunately still got error.
Thanks a lot

**Comment by djsaunde** [comment]
Hi @rachmadvwp, the `bindsnet-experiments` repo is not really being maintained at the moment. I'm using the `master` branch of BindsNET right now, and I'm getting a different error on the `diehl_and_cook_2015.py` script.

From the stack trace:

> print('\t%s: %.2f' % (scheme, float(np.mean(curves[scheme]))))

it looks like `curves[scheme]` is a `torch.Tensor` object, whereas `np.mean(...)` expects a `np.ndarray`. So, the fix should be to cast curves[scheme] to a `numpy` array, or to use `torch.mean(...)` instead.

**Comment by rachmadvwp** [comment]
Oh okay. I'll try to refine towards that direction. Thanks for the help. I'll close the issue for now.

**Comment by rachmadvwp** [comment]
Hi @djsaunde 
I´d Iike to ask,, if I want to capture whenever the pre- and postś-spike happen, how can i do that? Any function that can be used for it? I want to use it in the if condition like `if ( pre- or post-śpike ) :`.  
Thanks in advance.

**Comment by djsaunde** [comment]
Hi @rachmadvwp,

You could define a new learning rule which does this. Take a look at e.g. the [PostPre learning rule](https://github.com/Hananel-Hazan/bindsnet/blob/291eb3e5c2736d7f8842c820dfe41fbdc2fe10d7/bindsnet/learning/__init__.py#L112). A new learning rule can be custom-defined like:

```
from bindsnet.learning import LearningRule

class CustomLearningRule(LearningRule):
    def __init__(self,
        connection: AbstractConnection,
        nu: Optional[Union[float, Sequence[float]]] = None,
        weight_decay: float = 0.0,
        **kwargs
    ) -> None:
        ...

    def _connection_update(self, **kwargs):
        if self.source.s.any() or self.target.s.any():
            ...
```
Something like that. Just fill in your custom code. Let me know if you have any other questions.

**Comment by rachmadvwp** [comment]
I think these scripts `self.source.s.any()` or `self.target.s.any()` are what I'm looking for.
Because I was trying to find a function that can inform me whenever the spikes happen.
I'll try them out and close the issue at the moment. Thanks a lot.

**Comment by rachmadvwp** [comment]
Hi @djsaunde 
How long is the timing window for trace the traces in the following scripts in the [PostPre](https://github.com/Hananel-Hazan/bindsnet/blob/291eb3e5c2736d7f8842c820dfe41fbdc2fe10d7/bindsnet/learning/__init__.py#L112) rule?
```
source_x = self.source.x.view(-1)
target_x = self.target.x.view(-1)
```

Actually, I'd like to make a custom spike trace like the ones which can be called like above scripts.
How can I define that, especially defining the time window where the decay happens. I tried to look into class [Connection](https://github.com/Hananel-Hazan/bindsnet/blob/master/bindsnet/network/topology.py), but still didn't get it. Thanks in advance

**Comment by djsaunde** [comment]
Hi @rachmadvwp,

Spike traces are implemented at the [neuron level](https://github.com/Hananel-Hazan/bindsnet/blob/36dcb2610f4f76369c0bd89ea92d2c4ddae42201/bindsnet/network/nodes.py#L92). You can set a layer's spike trace time constant by passing in a custom value for `tc_trace` (short for _trace time constant_). For example:

**Comment by rachmadvwp** [comment]
Oh, so it was defined in the neuron level. I'll look into that and see whether I need to create the custom ones or no. Thanks so much

**Comment by rachmadvwp** [comment]
Hi @djsaunde 
Can we make use of the timing information in simulation, to bound a specific period of spike activity? I was thinking something like `if (time period x ms): monitor # spikes`. Thanks in advance

**Comment by djsaunde** [comment]
If you want to record state variables during simulation, you can use a `Monitor`, and set the `time` argument in the constructor equal to how many time steps you want to record activity for. The `Monitor` object will then record the most recent `time` steps in simulation. Is that what you're looking for?

**Comment by rachmadvwp** [comment]
I'm not sure, it could be. I just wanted to monitor the spike activity within a specific time duration, e.g., to monitor # post-spikes within 100 ms. Can we just use the `Monitor` function for this?

**Comment by djsaunde** [comment]
Yes, you can, although a `Monitor` is an object, not a function. Looking at the `record` function of the `Monitor` object:

```
    def record(self) -> None:
        # language=rst
        """
        Appends the current value of the recorded state variables to the recording.
        """
        if self.time is None:
            for v in self.state_vars:
                data = getattr(self.obj,v).unsqueeze(-1)
                self.recording[v] = torch.cat(
                    [self.recording[v].type(data.type()), data], -1
                )
        else:
            for v in self.state_vars:
                # Remove the oldest data and concatenate new data
                data = getattr(self.obj,v).unsqueeze(-1)
                self.recording[v] = torch.cat(
                    [self.recording[v][..., 1:].type(data.type()), data], -1
                )
```
If `time` is defined, then during simulation, the values of recorded state variables from the last `time` steps are recorded.

**Comment by rachmadvwp** [comment]
I'll look and try it out first. Thanks a lot for the help

**Comment by rachmadvwp** [comment]
Hi @djsaunde 
I'm looking into the learning rate, but I couldn't find in which segment of codes, the learning rate is being used for computation? I was looking into [this section](https://github.com/Hananel-Hazan/bindsnet/blob/master/bindsnet/network/topology.py#L158), but I couldn't understand how the value of the learning rate is being used here. Could you please explain that?
Thanks a lot and best regards.

**Comment by Huizerd** [comment]
It’s in the `LearningRule.update()` functions, are for example here:
https://github.com/Hananel-Hazan/bindsnet/blob/ac6cd40aae56c175e8229788af9b888895967c38/bindsnet/learning/__init__.py#L203

**Comment by rachmadvwp** [comment]
Ah, yeah... sorry, apparently I mixed up. What I wanted to ask is about the learning rate decay & weight decay

**Comment by Huizerd** [comment]
No worries! Weight decay happens in the `super.update()` of each learning rule:
https://github.com/Hananel-Hazan/bindsnet/blob/ac6cd40aae56c175e8229788af9b888895967c38/bindsnet/learning/__init__.py#L76

And I think that as of now, no learning rate decay is implemented. You might open a pull request though if you think you have a suitable approach for this!

**Comment by rachmadvwp** [comment]
Okay, thanks a lot for the help

**Comment by djsaunde** [comment]
You may implement your own weight decay by periodically multiplying the `nu` parameters of your `LearningRule` during training. E.g., see [this line of this script](https://github.com/djsaunde/bindsnet_experiments/blob/494f03ca80ff71692d03515e31b18df4ba774f2b/experiments/mnist/crop_locally_connected.py#L168).

**Comment by rachmadvwp** [comment]
> if self.source.s.any() or self.target.s.any():

Hi, I'd like to ask again.
The abovementioned scripts are for detecting if there any spikes in source / target populations.
How about if I want to check any pre- or post-synaptic spikes at each synaptic connection?
Thanks in advance

**Comment by djsaunde** [comment]
Hi @rachmadvwp,

> How about if I want to check any pre- or post-synaptic spikes at each synaptic connection?

I think you may be a little confused about how spikes are transmitted. If there is a spike at `self.source.s[i]` (source neuron `i`), then there is a spike at all synapses connecting from neuron `i` in the source population. Synapses don't have a "have-a" relationship with spikes, only neurons do. Does that make sense?

If you want to check for spikes that _happened at the same time_ in the source and target populations, you could write:

```
s1 = self.source.s
s2 = self.target.s
simultaneous = torch.ger(s1, s2)
```

The (i, j) entries of the `simultaneous` matrix will tell you which (source, target) neurons spiked at the same time.

**Comment by rachmadvwp** [comment]
Really sorry, it turns out that my question is confusing and not properly written to convey the message that I'm asking. I got what you explained actually.

I was asking, if I use `if self.source.s.any()', then any spike from different source neurons are detected right? for example, if I have 2 source neurons, then if I use 'if self.source.s.any() ', whenever either neuron-1 or neuron-2 fires, it will be true. What I wanted to ask was, can we detect the spikes at each neuron? For instance, if I just want to see the spike from neuron-1 only. If so, I would love to know if we can monitor spikes from each neuron in an efficient manner so that I don't need to use `for-loops`.

Thanks a lot

**Comment by rachmadvwp** [comment]
I'll try it and close the thread for now, thanks a lot for the help :)

**Comment by djsaunde** [comment]
Here's a simple example of `Monitor` usage that might help you get started:

```
import torch
import matplotlib.pyplot as plt

from bindsnet.network import Network
from bindsnet.network.nodes import Input, LIFNodes
from bindsnet.network.topology import Connection
from bindsnet.network.monitors import Monitor

from bindsnet.analysis.plotting import plot_spikes


plt.ioff()

time = 1000
n_input = 100
n_output = 10

network = Network()
network.add_layer(
    Input(n=n_input), name="X"
)
network.add_layer(
    LIFNodes(n=n_output, refrac=0), name="Y"
)
network.add_connection(
    Connection(
        source=network.layers["X"],
        target=network.layers["Y"],
    ),
    source="X",
    target="Y",
)
network.add_monitor(
    Monitor(network.layers["X"], state_vars=("s",)), name="X"
)
network.add_monitor(
    Monitor(network.layers["Y"], state_vars=("s",)), name="Y"
)

inpts = {
    "X": torch.bernoulli(0.05 * torch.rand(time, network.layers["X"].n)).bool()
}

network.run(inpts=inpts, time=time)

spikes = {
    layer: network.monitors[layer].get("s") for layer in network.layers
}

plot_spikes(spikes)
plt.show()
```

**Comment by rachmadvwp** [comment]
Hi, 

I'd like to ask & clarify something. In the experiment repo, I used the example and it uses [integration time](https://github.com/BINDS-LAB-UMASS/bindsnet_experiments/blob/8a20be9d1ede021b70ff95cc7e85024ff5a222db/experiments/mnist/diehl_and_cook_2015.py#L331) 'dt = 1' and [simulation time](    parser.add_argument('--time', default=350, type=int, help='simulation time')) 'time = 350'. Does it means that, 1 input image will be presented in Poisson-based spikes within 350ms,, and the STDP mechanism is monitored and calculated each dt=1 ms? If so, it means that basically the `torch.ger(source_x, target_s)` is calculated 350x within 1 presentation of 1 input image? Did I get it correct? If so, does it mean that if I increase the integration time, e.g.,  'dt = 10', the `torch.ger(source_x, target_s)` in STDP will be calculated each 10ms? 

If i get it wrong, could you please explain the correct one. 
Thanks in advance

**Comment by djsaunde** [comment]
> I'd like to ask & clarify something. In the experiment repo, I used the example and it uses integration time 'dt = 1' and simulation time 'time = 350'. Does it means that, 1 input image will be presented in Poisson-based spikes within 350ms,, and the STDP mechanism (i.e., torch.ger(source_x, target_s)) is monitored and calculated each dt=1 ms? Did I get it correct?

Yes, that's correct.

> If so, does it mean that if I increase the integration time, e.g., 'dt = 10', the torch.ger(source_x, target_s) in STDP will be calculated each 10ms?

This is correct, but if you increase the `dt`  to 10, all numerical integration operations (not only the STDP calculation) will only happen every 10ms. This is fine if your simulation doesn't rely on quantities with temporal resolutions <10ms, but I would be careful that changing this doesn't mess up the simulation of e.g., neuron voltages.

You would also have to change the input data to be of length `(simulation time) / dt`, or `350 / 10 = 35` in your case. You can do this by passing `dt=10.0` to the `poisson` encoding, e.g.: `poisson(datum=100*torch.rand(100), time=350, dt=10)`.

**Comment by rachmadvwp** [comment]
Thanks a lot for the explanation :)

**Comment by rachmadvwp** [comment]
Hi, I'd like to clarify small thing. In the Poisson generator (this [line](https://github.com/Hananel-Hazan/bindsnet/blob/1827e02266a26e44a517fbaaa1476a879dfe786b/bindsnet/encoding/encodings.py#L114)), is it correct that an input image encoded in rate 255Hz? Thanks in advance.

**Comment by djsaunde** [comment]
The passed-in data are treated as though they have Hz units. From the doc-string: "Inputs must be non-negative, and give the firing rate in Hz." So, if you pass in a tensor `[10, 50, 100, 255]`, the first will be converted to a spike train with firing rate 10Hz, the second, 50Hz, the third, 100Hz, and the fourth, 255Hz.
