### ISSUE TITLE
TensorboardX Logging

### ISSUE THREAD

**Issue by k-chaney** [Hananel-Hazan/bindsnet#267]
This functionality would mirror the matplotlib functionality that has been built out thus far. From my experience, it is far easier to log and view the logs using tensorboard vs matplotlib when running many experiments. In the `bindsnet.pipeline` setup, we would provide another `bindsnet.pipeline.PipelineAnalyzer` so it would be swappable with the `MatplotlibAnalyzer`.

@djsaunde Should these components be migrated into `bindsnet.analysis` instead of being kept in `bindsnet.pipeline`?

**Comment by djsaunde** [comment]
Yup, `bindsnet.analysis` would probably be a better home. Having tensorboard plots would be great; it's been on my radar for a while, but I don't have much time to work on BindsNET these days.

**Comment by k-chaney** [comment]
I have an initial set of components ready for this in `chaneyk/tensorboardX`. The primary awkward thing is the height of image for the spike trains (and voltages) inside of tensorboard.
