### ISSUE TITLE
"dataset = MNIST('data/mnist', download=True)" is wrong?

### ISSUE THREAD

**Issue by 666DZY666** [Hananel-Hazan/bindsnet#268]
TypeError: __init__() missing 1 required positional argument: 'label_encoder'?

when I give "None" for encoder,
and this "images, labels = dataset.get_train()",
AttributeError: 'torchvision_dataset_wrapper' object has no attribute 'get_train'?

**Comment by Hananel-Hazan** [comment]
There have been a few major PR lately that may have broken some things. This is one of them.
Please use BindsNET version 0.2.2 for the time being until we finish fixing the examples for the new changes.

**Comment by 666DZY666** [comment]
Thanks~

**Comment by djsaunde** [comment]
The datasets API has changed. It should still work, though. See for example [this script](https://github.com/Hananel-Hazan/bindsnet/blob/master/examples/mnist/minimal_mnist.py).
