### ISSUE TITLE
Trouble with --plot in examples

### ISSUE THREAD

**Issue by gpandrade** [Hananel-Hazan/bindsnet#282]
Hey y'all! Hope you're doing well.

I just noticed while trying to run the conv_mnist and eth_mnist examples that --plot seems to break things.

The error is:
OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
Abort trap: 6

**Comment by gpandrade** [comment]
pip list output:

Package                            Version  Location                                
---------------------------------- -------- ----------------------------------------
alabaster                          0.7.12   
anaconda-client                    1.7.2    
anaconda-navigator                 1.9.7    
anaconda-project                   0.8.2    
appnope                            0.1.0    
appscript                          1.0.1    
asn1crypto                         0.24.0   
astroid                            2.2.5    
astropy                            3.1.2    
atomicwrites                       1.3.0    
attrs                              19.1.0   
Babel                              2.6.0    
backcall                           0.1.0    
backports.os                       0.1.1    
backports.shutil-get-terminal-size 1.0.0    
basemap                            1.2.0    
beautifulsoup4                     4.7.1    
bindsnet                           0.2.4    /Users/andrade31/Desktop/bindsnet-master
bitarray                           0.8.3    
bkcharts                           0.2      
bleach                             3.1.0    
bokeh                              1.0.4    
boto                               2.49.0   
Bottleneck                         1.2.1    
certifi                            2019.3.9 
cffi                               1.12.2   
chardet                            3.0.4    
Click                              7.0      
cloudpickle                        0.8.0    
clyent                             1.2.2    
colorama                           0.4.1    
conda                              4.6.14   
conda-build                        3.17.8   
conda-verify                       3.1.1    
contextlib2                        0.5.5    
cryptography                       2.6.1    
cycler                             0.10.0   
Cython                             0.29.6   
cytoolz                            0.9.0.1  
dask                               1.1.4    
decorator                          4.4.0    
defusedxml                         0.5.0    
distributed                        1.26.0   
docutils                           0.14     
entrypoints                        0.3      
et-xmlfile                         1.0.1    
fastcache                          1.0.2    
filelock                           3.0.10   
Flask                              1.0.2    
future                             0.17.1   
gevent                             1.4.0    
glob2                              0.6      
gmpy2                              2.0.8    
greenlet                           0.4.15   
gym                                0.12.5   
h5py                               2.9.0    
heapdict                           1.0.0    
hollywood                          0.0.1    
html5lib                           1.0.1    
idna                               2.8      
imageio                            2.5.0    
imagesize                          1.1.0    
importlib-metadata                 0.0.0    
ipykernel                          5.1.0    
ipython                            7.4.0    
ipython-genutils                   0.2.0    
ipywidgets                         7.4.2    
isort                              4.3.16   
itsdangerous                       1.1.0    
jdcal                              1.4      
jedi                               0.13.3   
Jinja2                             2.10     
jsonschema                         3.0.1    
jupyter                            1.0.0    
jupyter-client                     5.2.4    
jupyter-console                    6.0.0    
jupyter-core                       4.4.0    
jupyterlab                         0.35.4   
jupyterlab-server                  0.2.0    
keyring                            18.0.0   
kiwisolver                         1.0.1    
lazy-object-proxy                  1.3.1    
libarchive-c                       2.8      
lief                               0.9.0    
llvmlite                           0.28.0   
locket                             0.2.0    
lxml                               4.3.2    
MarkupSafe                         1.1.1    
matplotlib                         3.1.0    
mccabe                             0.6.1    
mistune                            0.8.4    
mkl-fft                            1.0.10   
mkl-random                         1.0.2    
more-itertools                     6.0.0    
mpmath                             1.1.0    
msgpack                            0.6.1    
multipledispatch                   0.6.0    
navigator-updater                  0.2.1    
nbconvert                          5.4.1    
nbformat                           4.4.0    
networkx                           2.2      
nltk                               3.4      
nose                               1.3.7    
notebook                           5.7.8    
numba                              0.43.1   
numexpr                            2.6.9    
numpy                              1.16.2   
numpydoc                           0.8.0    
obspy                              1.1.1    
olefile                            0.46     
opencv-python                      4.1.0.25 
openpyxl                           2.6.1    
packaging                          19.0     
pandas                             0.24.2   
pandocfilters                      1.4.2    
parso                              0.3.4    
partd                              0.3.10   
path.py                            11.5.0   
pathlib2                           2.3.3    
patsy                              0.5.1    
pep8                               1.7.1    
pexpect                            4.6.0    
pickleshare                        0.7.5    
Pillow                             5.4.1    
pip                                19.0.3   
pkginfo                            1.5.0.1  
pluggy                             0.9.0    
ply                                3.11     
prometheus-client                  0.6.0    
prompt-toolkit                     2.0.9    
protobuf                           3.8.0    
psutil                             5.6.1    
ptyprocess                         0.6.0    
py                                 1.8.0    
pycodestyle                        2.5.0    
pycosat                            0.6.3    
pycparser                          2.19     
pycrypto                           2.6.1    
pycurl                             7.43.0.2 
pyflakes                           2.1.1    
pyglet                             1.3.2    
Pygments                           2.3.1    
pylint                             2.3.1    
pyodbc                             4.0.26   
pyOpenSSL                          19.0.0   
pyparsing                          2.3.1    
pyproj                             1.9.5.1  
pyrsistent                         0.14.11  
pyshp                              2.1.0    
PySocks                            1.6.8    
pytest                             4.3.1    
pytest-arraydiff                   0.3      
pytest-astropy                     0.5.0    
pytest-doctestplus                 0.3.0    
pytest-openfiles                   0.3.2    
pytest-remotedata                  0.3.1    
python-dateutil                    2.8.0    
pytz                               2018.9   
PyWavelets                         1.0.2    
PyYAML                             5.1      
pyzmq                              18.0.0   
QtAwesome                          0.5.7    
qtconsole                          4.4.3    
QtPy                               1.7.0    
requests                           2.21.0   
rope                               0.12.0   
ruamel-yaml                        0.15.46  
scikit-image                       0.14.2   
scikit-learn                       0.20.3   
scipy                              1.2.1    
seaborn                            0.9.0    
Send2Trash                         1.5.0    
setuptools                         40.8.0   
simplegeneric                      0.8.1    
singledispatch                     3.4.0.3  
six                                1.12.0   
snowballstemmer                    1.2.1    
sortedcollections                  1.1.2    
sortedcontainers                   2.1.0    
soupsieve                          1.8      
Sphinx                             1.8.5    
sphinxcontrib-websupport           1.1.0    
spyder                             3.3.3    
spyder-kernels                     0.4.2    
SQLAlchemy                         1.3.1    
statsmodels                        0.9.0    
sympy                              1.3      
tables                             3.5.1    
tblib                              1.3.2    
tensorboardX                       1.7      
terminado                          0.8.1    
testpath                           0.4.2    
toolz                              0.9.0    
torch                              1.1.0    
torchvision                        0.3.0    
tornado                            6.0.2    
tqdm                               4.31.1   
traitlets                          4.3.2    
unicodecsv                         0.14.1   
urllib3                            1.24.1   
wcwidth                            0.1.7    
webencodings                       0.5.1    
Werkzeug                           0.14.1   
wheel                              0.33.1   
widgetsnbextension                 3.4.2    
wrapt                              1.11.1   
wurlitzer                          1.0.2    
xlrd                               1.2.0    
XlsxWriter                         1.1.5    
xlwings                            0.15.4   
xlwt                               1.3.0    
zict                               0.1.4    
zipp                               0.3.3

**Comment by Hananel-Hazan** [comment]
There have been a few major PR lately that may have broken some things. This could be one of them.
Please use BindsNET version 0.2.2 for the time being until we finish fixing the examples for the new changes.

**Comment by djsaunde** [comment]
According to personal communcation, the error is fixed when setting `KMP_DUPLICATE_LIB_OK=TRUE` as recommended by the error message.

**Comment by djsaunde** [comment]
Related: https://github.com/dmlc/xgboost/issues/1715. The error appears to be specific to MacOS, and seems to originate from `matplotlib`. One solution is:

```
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
```

Another solution may be to issue `conda install nomkl`.
