### ISSUE TITLE
connecting neurons within a layer

### ISSUE THREAD

**Issue by WongyuLee1729** [Hananel-Hazan/bindsnet#292]
Hello, I'm just wondering if there is any way to connect neurons in a layer once after we set the layer.
i.e. set a layer of neurons, say 100 neurons in the layer, and I want to connection a specific neuron to the other one in the layer. 

Thank you.

**Comment by djsaunde** [comment]
Yes, you can do this with a `Connection` from the layer to itself. E.g., 

```
layer = LIFNodes(n=100)
w = ...  # Define in-layer connectivity
connection = Connection(source=layer, target=layer, w=w)
```
