### ISSUE TITLE
Error in Importing PoissionEncoder

### ISSUE THREAD

**Issue by CoolJadeGuo** [Hananel-Hazan/bindsnet#295]
`
Traceback (most recent call last): 
 File "eth_mnist.py", line 18, in <module>
 from bindsnet.encoding import PoissonEncoder
`

**Comment by djsaunde** [comment]
Hi @CoolJadeGuo, we're in the process of fixing the examples to conform with a new version of BindsNET (yet to be released on PyPI). To import `PoissonEncoder`, get the latest code by cloning the master branch.

**Comment by Hananel-Hazan** [comment]
should be ok in #294

**Comment by CoolJadeGuo** [comment]
Many thanks for your help. But the same issue still exists after I cloned the latest master branch and run eth_mnist.py:
`Traceback (most recent call last):
  File "eth_mnist.py", line 16, in <module>
    from bindsnet.encoding import PoissonEncoder
ImportError: cannot import name 'PoissonEncoder'`

**Comment by dee0512** [comment]
@CoolJadeGuo I just tested the code on the latest branch. There does not seem to be an issue.  Did you remember to reinstall the Bindsnet on the latest branch?

try:

`pip install -e .`

or 

`pip install .`

**Comment by dee0512** [comment]
Just saw that the main branch was updated 3 hours ago, maybe that fixed it.
