### ISSUE TITLE
Issue with importing BernoulliEncoder and EnvironmentPipeline

### ISSUE THREAD

**Issue by kuffmode** [Hananel-Hazan/bindsnet#299]
Hi all,
I wanted to try Space Invaders but I keep on getting these errors with respect to 2 classes:
```
from bindsnet.pipeline import EnvironmentPipeline
from bindsnet.encoding import BernoulliEncoder


ImportError: cannot import name 'EnvironmentPipeline'
ImportError: cannot import name 'BernoulliEncoder'
```
So I was wondering if you know what can be the issue. I tried some troubleshoots:
Reinstalling the repo
using python 2 and 3
checking the paths

**Comment by Hananel-Hazan** [comment]
There have been a few major PR lately that may have broken some things. This could be one of them.

Can you try running this scrip using BindsNET version 0.2.2?

**Comment by djsaunde** [comment]
By the way, these commands work if you're working off of the current master branch.

**Comment by kuffmode** [comment]
I'm using BindsNET 0.2.4 so I'll give 0.2.2 a try and let you know. Thanks
