### ISSUE TITLE
AttributeError: 'TorchvisionDatasetWrapper' object has no attribute 'get_train'

### ISSUE THREAD

**Issue by Qlina** [Hananel-Hazan/bindsnet#300]
Hi, 
I tried using this [script](https://github.com/djsaunde/bindsnet_experiments/blob/master/experiments/mnist/diehl_and_cook_2015.py) to test, but a problem encountered.
`Traceback (most recent call last):
  File "diehl_and_cook_2015.py", line 424, in <module>
    main(**args)
  File "diehl_and_cook_2015.py", line 160, in main
    images, labels = dataset.get_train()
AttributeError: 'TorchvisionDatasetWrapper' object has no attribute 'get_train'`

I can't find the function "get_train" in the code.
Could you tell how to solve this problem？
Thanks！

**Comment by Hananel-Hazan** [comment]
There have been a few major PR lately that may have broken some things. This could be one of them.

Can you try running this scrip using BindsNET version 0.2.2?

**Comment by Qlina** [comment]
Thank you for your reply!
I tried running this script using BindsNET version 0.2.2, however some function the scrip need not exist in version 0.2.2.
So I copied the "get_train()" function from BindsNET version 0.2.2 "dataset/__init__.py", to the latest version BindsNET 0.2.4 "dataset/torchvision_wrapper/ class TorchvisionDatasetWrapper(ds_type)". 
Programs still don't work properly.
The function I copied is:
`    @abstractmethod
    def get_train(self) -> Tuple[Any, ...]:
        # language=rst
        """
        Abstract method stub for fetching training data from a dataset.
        """
        pass`
The error traceback is:
`Traceback (most recent call last):
  File "diehl_and_cook_2015.py", line 423, in <module>
    main(**args)
  File "diehl_and_cook_2015.py", line 159, in main
    images, labels = dataset.get_train()
TypeError: 'NoneType' object is not iterable`

**Comment by djsaunde** [comment]
In general, the scripts in the `bindsnet_experiments` repository are out-of-date, and aren't expected to work.
