### ISSUE TITLE
Is ONNX supported?

### ISSUE THREAD

**Issue by dizcza** [Hananel-Hazan/bindsnet#304]
I found ONNX is mentioned in your paper 2018 in a todo list. Is saving BindsNET models in ONNX format already implemented? That would be very beneficial for my project, where I want to use SNN to navigate Arduino-like robot.
Thank you.

**Comment by djsaunde** [comment]
It's not supported (we haven't had a use case for it yet), but we are open to PRs!

**Comment by Hananel-Hazan** [comment]
Pytorch that support it [link](https://pytorch.org/docs/master/onnx.html), but BindsNET is yet to support it..
