### ISSUE TITLE
setting different reset values for each neurons

### ISSUE THREAD

**Issue by WongyuLee1729** [Hananel-Hazan/bindsnet#307]
In the MNIST example, DiehlAndCook2015, I'm trying to give different reset values for each neuron after spike occurs. However, the code is grouped by layers so that, in a layer, it seems not possible to pick out specific neuron and give a different reset  value. 
for example, given the following Bindsnet code
**===========================================================
self.add_layer(DiehlAndCookNodes(n=self.n_neurons, traces=True, rest=-65.0, reset=-60.0, thresh=-52.0, refrac=5,
                                         decay=1e-2, trace_tc=5e-2, theta_plus=theta_plus, theta_decay=theta_decay),
                       name='Ae') 
===========================================================**
In[20]: network.layers['Ae'].reset
Out[20]: tensor(-60.)
and 
In[21]: network.layers['Ae'].n
Out[21]: 200                            # number of neurons 
These are just constant values

Please let me know how to handle this case. 
Thank you.

**Comment by djsaunde** [comment]
Hi @WongyuLee1729,

It is possible! You can simple pass in a 1D tensor of values for the `reset` argument. For example, to use reset values sampled from Normal(-60, 1):

```
layer = LIFNodes(n=100, reset=-60.0 + torch.randn(100))
```

This applies to other parameters as well; e.g., `rest`, `thresh`, `refrac`, etc.

**Comment by WongyuLee1729** [comment]
> Hi @WongyuLee1729,
> 
> It is possible! You can pass in a 1D tensor of values for the `reset` argument. For example, to use reset values sampled from Normal(-60, 1):
> 
> ```
> layer = LIFNodes(n=100, reset=-60.0 + torch.randn(100))
> ```
> 
> This applies to other parameters as well; e.g., `rest`, `thresh`, `refrac`, etc.

Thank you so much! It really helped me
