### ISSUE TITLE
Trouble running Breakout example

### ISSUE THREAD

**Issue by dizcza** [Hananel-Hazan/bindsnet#308]
I'm looking for a RL + SNN example and I found breakout directory in examples. Both scripts don't run (at least because `Pipeline` class does not exist at all).
I changed
`Pipeline` -> `EnvironmentPipeline`,
`pipeline.step()` -> `pipeline.env_step()` (also tried `pipeline.train()` without the loop),
but still I see the error I don't know how to fix:
```python
Traceback (most recent call last):
  File "/home/dizcza/PycharmProjects/other/bindsnet/examples/breakout/breakout.py", line 57, in <module>
    pipeline.env_step()
  File "/home/dizcza/PycharmProjects/other/bindsnet/bindsnet/pipeline/environment_pipeline.py", line 120, in env_step
    self.action = self.action_function(self, output=self.output)
  File "/home/dizcza/PycharmProjects/other/bindsnet/bindsnet/pipeline/action.py", line 73, in select_softmax
    ), "EnvironmentPipeline has not attribute named: spike_record."
AssertionError: EnvironmentPipeline has not attribute named: spike_record.
```

If Breakout is no longer supported, are there any other RL examples, ported in BindsNET? I'm interested in training SNN, not just an inference.

**Comment by Hananel-Hazan** [comment]
Thanks for using BindsNET. 
Can you try running this scrip using BindsNET version 0.2.2?
Those examples need to be update to be compatible with the new changes. 
Hopefully we will be update all of the examples in the near future.

**Comment by dizcza** [comment]
I confirm it works with 0.2.2.
I noticed you [claim](https://github.com/Hananel-Hazan/bindsnet/issues/265) that converting trained ANN to SNN does not drop the accuracy significantly. Hope it's true for RL models as well. I might ask a few questions in the issue I mentioned about converting Breakout trained model to SNN.

You can close this issue or leave it open until you fix the example. I noticed the same behavior in other examples and it needs a lot of things to fix, and so I guess it might take a while.

**Comment by djsaunde** [comment]
> I noticed you claim that converting trained ANN to SNN does not drop the accuracy significantly.

**Comment by djsaunde** [comment]
> I noticed you claim that converting trained ANN to SNN does not drop the accuracy significantly.
It's more than just a claim, it's been verified for certain datasets + classes of ANNs: https://www.frontiersin.org/articles/10.3389/fnins.2017.00682/full?report=reader.

> I might ask a few questions in the issue I mentioned about converting Breakout trained model to SNN.
The Breakout script doesn't result in good performance on the game, it just demonstrates that you can hook up a SNN to OpenAI Gym environments.

**Comment by djsaunde** [comment]
As for fixing the examples, it is unfortunately not a high priority at the moment.

**Comment by dizcza** [comment]
Thanks for fixing the examples.
