### ISSUE TITLE
Torchvision wrapper does not handle cuda

### ISSUE THREAD

**Issue by dee0512** [Hananel-Hazan/bindsnet#315]
datasets/torchvision_wrapper.py does not convert the image to cuda (device) before passing the image to encodings.py funcions. 

I think we should add _gpu versions of the datasets in datasets/__init__.py

or a way to pass device if anyone else has a better idea.

**Comment by djsaunde** [comment]
Hm, I don't think they should be on the GPU. The typical pattern is to load data on the CPU, and transfer them to (pinned) GPU memory as needed. See e.g. here: https://discuss.pytorch.org/t/when-to-set-pin-memory-to-true/19723.

**Comment by dee0512** [comment]
In that case, do not forget to convert the data from dataloader to device. For example in bindsnet_examples the batch lc_snn example. I will fix it.

**Comment by djsaunde** [comment]
Those examples aren't being maintained, and I don't plan to update them anytime soon.
