### ISSUE TITLE
node.s is set to CPU

### ISSUE THREAD

**Issue by dee0512** [Hananel-Hazan/bindsnet#316]
[https://github.com/Hananel-Hazan/bindsnet/blob/dbdd8dbdae14efbce4263e7ed3df0337080679c1/bindsnet/network/nodes.py#L64](url)

This line is setting the node.s to cpu by default. We are setting the type by node.s.device in other places. Like here:[https://github.com/Hananel-Hazan/bindsnet/blob/dbdd8dbdae14efbce4263e7ed3df0337080679c1/bindsnet/network/network.py#L226](url)

Can we go back to it being torch.zeros?

@djsaunde

**Comment by djsaunde** [comment]
I think it is typical PyTorch practice to create the network on the CPU, and then call the `to()` method to put it on the GPU. For example:

```
network = Network()
...
network.add_layer(...)
network.add_connection(...)
...
network.to("cuda")
```
