### ISSUE TITLE
Small error in eth_mnist.py?

### ISSUE THREAD

**Issue by khengyeww** [Hananel-Hazan/bindsnet#319]
When running eth_mnist.py with only --plot option, the error below occurred.
```
Traceback (most recent call last):
  File "eth_mnist.py", line 247, in <module>
    image, inpt, label=labels[step], axes=inpt_axes, ims=inpt_ims
IndexError: list index out of range
```

I think this is due to 
https://github.com/Hananel-Hazan/bindsnet/blob/39105a49265e2e2532f0b91b3e31086dc77cce4a/examples/mnist/eth_mnist.py#L220
which clears the list at every update interval.

<br>

My suggested solution is that to either remove the line220 mentioned above, or change the `labels[step]` to `labels[step % update_interval]` in 
https://github.com/Hananel-Hazan/bindsnet/blob/39105a49265e2e2532f0b91b3e31086dc77cce4a/examples/mnist/eth_mnist.py#L246-L248
if clearing the list at every update interval is intended?

**Comment by djsaunde** [comment]
Hi @khengyeww, I just pushed a fix to the `master` branch. Let me know if you have any other problems!
