### ISSUE TITLE
can u give an example for object detection

### ISSUE THREAD

**Issue by apple1987** [Hananel-Hazan/bindsnet#321]
At present, spiking neural network is mainly used for object recognition.
As shown in the title, Can U give an example for object detection? just as spiking yolo,thanks.

**Comment by djsaunde** [comment]
Unfortunately, I'm unaware of any spiking neural network implementation of object detection, and we certainly don't have one in BindsNET. A quick Google search turned up [this]https://arxiv.org/abs/1903.06530). We would love to see an implementation using BindsNET!
