### ISSUE TITLE
error in eth_mnist example

### ISSUE THREAD

**Issue by ati6868** [Hananel-Hazan/bindsnet#323]
Hi 
when i was going to run eth_mnist.py 
i get this error:
` File "C:\Users\Ati\Desktop\bindsnet-master\examples\mnist\eth_mnist.py", line 92, in <module>
 inpt_shape=(1, 28, 28),
TypeError: __init__() got an unexpected keyword argument 'inpt_shape'`

Could you please help me on this why i am getting this error?

**Comment by djsaunde** [comment]
Hi @ati6868,

I can't seem to reproduce your error. Did you install the latest version of BindsNET with `pip install bindsnet -U` or by cloning the repo and doing `pip install -e .` in the top-level directory? Could you send me the output of `pip list`?

**Comment by ati6868** [comment]
Thanks @djsaunde  for your response
i installed BindsNET  `with pip install bindsnet -U` already
but here are the version of it
`bindsnet= 0.2.4` 
`torch=1.1.0`
`torchvision=0.3.0`

plus when i am going to install it agian
i get this error:
`ERROR: Could not find a version that satisfies the requirement torch>=1.2.0 (from 
bindsnet) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)

ERROR: No matching distribution found for torch>=1.2.0 (from bindsnet)`

**Comment by djsaunde** [comment]
Hm, `torch 1.2.0` is out, so I don't know why you're getting that error. You should try just `pip install torch==1.2.0`, and if that fails, look for help on installing the current version of `torch` elsewhere; e.g., [here](https://github.com/pytorch/pytorch).

**Comment by ati6868** [comment]
I uninstalled completely torch , bindsnet and then i installed them again  and now it's working for me
thank you @djsaunde
