### ISSUE TITLE
Spiking auto-encoders with BindsNet

### ISSUE THREAD

**Issue by ati6868** [Hananel-Hazan/bindsnet#328]
Hi 
In BindsNET , is that possible that we make an autoencoder for implementing on mnist
(An autoencoder for spiking neural networks)
Could i create a simple autoencoder in pytorch(that is for ANN) then use Conversion.py module to convert it to spiking autoencoder??

Thank you

**Comment by Hananel-Hazan** [comment]
In principle it is possible. 
Your welcome to try and share the results and experience with us.
