### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'path' 

### ISSUE THREAD

**Issue by leleyi** [Hananel-Hazan/bindsnet#330]
I am new, I wanna kown how can I deal this

**Comment by leleyi** [comment]
dataset = MNIST(root=data_path, download=True) 
 why there dont have the method  "get_train()"

**Comment by coopersigrist** [comment]
The code has been refactored but the examples are still being worked on, check out the eth_mnist example for a working example. We are now using wrappers around torchvision datasets so get_train isn't necessary

**Comment by leleyi** [comment]
Thank you very much.
