### ISSUE TITLE
synapse connection ordering between neurons

### ISSUE THREAD

**Issue by WongyuLee1729** [Hananel-Hazan/bindsnet#334]
Hello, 
I have a question about ordering synapse connection between neuron layers. 
For example, in the SNN MNIST example, there are 3 layers: X, Ae, Ai
And they are connected in the following order 
[X, Ae] => [Ae, Ai] => [Ai, Ae]. 

Now I'm wondering after [Ai, Ae] connection occurs, can I connect new layer from Ae ?  
How can I set the order the connection?? 

Thank you. 
Wongyu

**Comment by djsaunde** [comment]
Hi @WongyuLee1729,

I'm not sure what you mean by "order"; the layers are connected, but there is no ordering to the connections themselves. Simulation takes place synchronously, meaning every layer is updated on each time step using the network state from the previous time step.

There is nothing stopping you from making a connection from layer `Ae` to another layer, and the order which it's added in doesn't matter.
