### ISSUE TITLE
Adding new dataset

### ISSUE THREAD

**Issue by lqmanhosni** [Hananel-Hazan/bindsnet#337]
How do i add new dataset? The dataset that i want to add is in bmp format. So can i just upload it or need to convert into specific format? Can you explain to me the process step by step?

**Comment by djsaunde** [comment]
Take a look at the [PyTorch tutorials](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html) for reading in custom datasets, and then wrap the dataset for conversion into spiking data using [this wrapper](https://github.com/Hananel-Hazan/bindsnet/blob/7ab6d8314310755c18f2a5f474b5d24a2c6a9295/bindsnet/datasets/torchvision_wrapper.py#L18). You can then load and batch your data using [a time-aware data loader](https://github.com/Hananel-Hazan/bindsnet/blob/7ab6d8314310755c18f2a5f474b5d24a2c6a9295/bindsnet/datasets/dataloader.py#L6).

**Comment by lqmanhosni** [comment]
Okay thank you very much
