### ISSUE TITLE
reset_state_variables in breakout example

### ISSUE THREAD

**Issue by keiserjmlps** [Hananel-Hazan/bindsnet#341]
Hi,

When running the breakout example, I get the following error:

**AttributeError: 'EnvironmentPipeline' object has no attribute 'reset_state_variables'**

in the portion of the code:

```
# Run environment simulation for 100 episodes.
for i in range(100):
    total_reward = 0
    pipeline.reset_state_variables()
    is_done = False
    while not is_done:
        result = pipeline.env_step()
        pipeline.step(result)
        reward = result[1]
        total_reward += reward
        is_done = result[2]
    print(f"Episode {i} total reward:{total_reward}")

```

Any suggestions on how to successfully run this (and other examples)?

Thanks,
James.

**Comment by djsaunde** [comment]
Hi @keiserjmlps, I'm not experiencing this problem on my end. Could you update to the latest version of BindsNET? `pip install -U bindsnet` should do the trick, or clone the master repo to stay up-to-date on changes.

**Comment by keiserjmlps** [comment]
Thank you for the quick reply.  It looks like things are working now!!

Thanks,

James.

________________________________
