### ISSUE TITLE
How can we test the trained network on the test dataset?

### ISSUE THREAD

**Issue by kevinlemon** [Hananel-Hazan/bindsnet#73]
Hello. 
In your './examples/eth_mnist.py', you showed how to train the SNN. How can we evaluate the trained SNN on the test dataset?

**Comment by djsaunde** [comment]
Hi @kevinlemon,

Yes, that's approximately what we do. See [this repository](https://github.com/djsaunde/bindsnet_experiments) for an example for the Diehl and Cook 2015 network. We end up tweaking the network a bit to make it behave a little more predictably during the test phase (e.g., by removing STDP updates).

P.S. More experiments will be added soon.

**Comment by kevinlemon** [comment]
Great! Thanks.

**Comment by xhongtang** [comment]
Take the liberty of disturbing.
As I see that there seems to be a cifar10 data set in your project.Could i ask what the test results of this network on cifar10 are like?
I want to try out the effect of this network on cifar10.
Did you have ever had a test?

**Comment by djsaunde** [comment]
Hi @xhongtang, we weren't able to get any good results with CIFAR-10. The best we got was a bit better than random (~10%). We have an example script [here](https://github.com/djsaunde/bindsnet_experiments/blob/master/experiments/cifar10/diehl_and_cook_2015.py) (it may not be working; let me know if not and I'll fix it).
