### ISSUE TITLE
How to save the trained network weights ?

### ISSUE THREAD

**Issue by manjunaths** [Hananel-Hazan/bindsnet#83]
I trained the network and after 60000 steps the conv_mnist.py just exited. There was no weights file that I could find. How to test the network with our own inputs ? Or is it supposed to be trained via a notebook file and we keep it 'live' and give custom test images ?

**Comment by djsaunde** [comment]
Hi @manjunaths,

`conv_mnist.py` is just an example script. We haven't provided *any* guarantees about what it should do; it simply is an example of how BindsNET can be used.

Check out [this script](https://github.com/djsaunde/bindsnet_experiments/blob/master/scripts/mnist/diehl_and_cook_2015.py) for an example of how BindsNET's `network.save()` and `load_network()` functions can be used to save and load network objects. Notice that we also use `pickle` to dump certain "auxiliary" data (used for classification purposes) to disk as well.

**Comment by manjunaths** [comment]
Thank you for the information. I am going to close this issue now.
