### ISSUE TITLE
Have trouble running the mnist example

### ISSUE THREAD

**Issue by Nuullll** [Hananel-Hazan/bindsnet#97]
File "examples/mnist/eth_mnist.py", line 159,
Function `get_ngram_counts` is not defined.

**Comment by djsaunde** [comment]
Hi @Nuullll,

We just updated the master branch to fix this.

**Comment by Nuullll** [comment]
I don't think the bug has been fixed :)

**Comment by djsaunde** [comment]
@hqkhan It looks like `get_ngram_counts` should be replaced with `update_ngram_scores`? Could you fix this?

![image](https://user-images.githubusercontent.com/1245942/42821739-42199e18-89a7-11e8-83f7-0a3d3c49c052.png)

**Comment by hqkhan** [comment]
Hi @Nuullll, I just updated master with the correct implementation. The code that produced the error should not have been there. I tested `eth_mnist.py` and it works on my end now. 

Please let me know if you're still having issues.
